"""File storage abstraction.

Local disk now, Azure Blob later. Roughly a hundred lines of indirection that
turn a miserable week of find-and-replace into a configuration change: business
logic never sees a path, only an opaque ``storage_key``.

**Local storage makes the application server stateful.** Two instances behind a
load balancer need a shared volume, and a container restart without a mounted
volume loses every screenshot. Acceptable for a single instance; the constraint
disappears entirely on Azure Blob.
"""

from __future__ import annotations

import hashlib
import re
import uuid
from abc import ABC, abstractmethod
from datetime import UTC, datetime
from pathlib import Path

from app.core.config import settings
from app.core.errors import ValidationFailedError
from app.core.logging import get_logger

logger = get_logger(__name__)

#: Extension allowlist. Checked alongside the declared content type -- neither
#: alone is trustworthy, since both come from the client.
ALLOWED_EXTENSIONS: frozenset[str] = frozenset(
    {".png", ".jpg", ".jpeg", ".gif", ".webp", ".pdf", ".txt", ".log", ".csv", ".json"}
)

ALLOWED_CONTENT_TYPES: frozenset[str] = frozenset(
    {
        "image/png",
        "image/jpeg",
        "image/gif",
        "image/webp",
        "application/pdf",
        "text/plain",
        "text/csv",
        "application/json",
    }
)

#: Magic bytes for the binary formats we accept. A file claiming to be a PNG
#: that does not start with the PNG signature is rejected -- the declared
#: content type is client input and cannot be trusted on its own.
_SIGNATURES: dict[str, tuple[bytes, ...]] = {
    "image/png": (b"\x89PNG\r\n\x1a\n",),
    "image/jpeg": (b"\xff\xd8\xff",),
    "image/gif": (b"GIF87a", b"GIF89a"),
    "image/webp": (b"RIFF",),
    "application/pdf": (b"%PDF-",),
}

_SAFE_NAME = re.compile(r"[^A-Za-z0-9._-]")


class FileStorage(ABC):
    """The interface business logic depends on."""

    @abstractmethod
    async def save(self, key: str, data: bytes, content_type: str) -> None: ...

    @abstractmethod
    async def read(self, key: str) -> bytes: ...

    @abstractmethod
    async def delete(self, key: str) -> None: ...

    @abstractmethod
    async def signed_url(self, key: str, ttl_seconds: int) -> str | None:
        """A short-lived direct URL, or None when the backend cannot issue one.

        Local storage returns None, so downloads stream through a
        permission-checked endpoint instead.
        """


class LocalFileStorage(FileStorage):
    def __init__(self, root: str | None = None) -> None:
        self._root = Path(root or settings.STORAGE_LOCAL_PATH).resolve()
        self._root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        # The key is generated by this module, never supplied by a client, but
        # the containment check stays as a second line of defence against a
        # future caller passing something through.
        candidate = (self._root / key).resolve()
        if not candidate.is_relative_to(self._root):
            raise ValidationFailedError("Invalid storage key.")
        return candidate

    async def save(self, key: str, data: bytes, content_type: str) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    async def read(self, key: str) -> bytes:
        path = self._path(key)
        if not path.exists():
            raise FileNotFoundError(key)
        return path.read_bytes()

    async def delete(self, key: str) -> None:
        path = self._path(key)
        path.unlink(missing_ok=True)

    async def signed_url(self, key: str, ttl_seconds: int) -> str | None:
        return None


class AzureBlobStorage(FileStorage):
    """Placeholder for the Azure implementation.

    Deliberately raising rather than silently falling back: a misconfigured
    STORAGE_BACKEND should fail loudly at startup, not quietly write files to a
    disk that nobody backs up.
    """

    def __init__(self) -> None:
        raise NotImplementedError(
            "Azure Blob storage is not implemented yet. Set STORAGE_BACKEND=local."
        )

    async def save(self, key: str, data: bytes, content_type: str) -> None:
        raise NotImplementedError

    async def read(self, key: str) -> bytes:
        raise NotImplementedError

    async def delete(self, key: str) -> None:
        raise NotImplementedError

    async def signed_url(self, key: str, ttl_seconds: int) -> str | None:
        raise NotImplementedError


def get_storage() -> FileStorage:
    if settings.STORAGE_BACKEND == "azure_blob":
        return AzureBlobStorage()
    return LocalFileStorage()


# ------------------------------------------------------------- validation


def build_storage_key(tenant_id: uuid.UUID, filename: str) -> str:
    """An opaque key with no client-controlled path component.

    Sharded by tenant and date so a directory never accumulates millions of
    entries, which some filesystems handle badly.
    """
    today = datetime.now(UTC)
    suffix = Path(filename).suffix.lower()[:10]
    return f"{tenant_id}/{today:%Y/%m}/{uuid.uuid4().hex}{suffix}"


def safe_display_name(filename: str) -> str:
    """Sanitise the original name, kept as metadata only."""
    name = Path(filename).name
    return _SAFE_NAME.sub("_", name)[:255] or "file"


def validate_upload(filename: str, content_type: str, data: bytes) -> None:
    """Reject anything outside the allowlist, and anything lying about itself."""
    if len(data) == 0:
        raise ValidationFailedError("The file is empty.")
    if len(data) > settings.MAX_UPLOAD_BYTES:
        limit_mb = settings.MAX_UPLOAD_BYTES // (1024 * 1024)
        raise ValidationFailedError(f"Files must be {limit_mb} MB or smaller.")

    suffix = Path(filename).suffix.lower()
    if suffix not in ALLOWED_EXTENSIONS:
        raise ValidationFailedError(f"'{suffix or filename}' is not an allowed file type.")

    base_type = content_type.split(";")[0].strip().lower()
    if base_type not in ALLOWED_CONTENT_TYPES:
        raise ValidationFailedError(f"'{base_type}' is not an allowed content type.")

    expected = _SIGNATURES.get(base_type)
    if expected and not any(data.startswith(sig) for sig in expected):
        # The declared type and the actual bytes disagree.
        raise ValidationFailedError("The file contents do not match its declared type.")


def checksum(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()
